#! /usr/bin/python

# Start up Tor just long enough for it to download the relay
# directory.  Including a cache of the directory in the package
# significantly speeds up startup when it matters (i.e. when the
# Selenium controller is twiddling its thumbs).

import errno
import os
import subprocess
import sys
import tempfile

def main():
    cwd = os.getcwd()
    libpath = os.environ.get("LD_LIBRARY_PATH")
    os.environ["LD_LIBRARY_PATH"] = \
        os.path.join(cwd, "Lib") + \
        ((":" + libpath) if libpath is not None else "")

    try:
        os.mkdir("Data/Tor/data", 0700)
    except EnvironmentError, e:
        if e.errno != errno.EEXIST:
            raise

    with tempfile.NamedTemporaryFile(dir=".", prefix="torrc_") as torrc:
        torrc.write("""\
DataDirectory ./Data/Tor/data
GeoIPFile ./Data/Tor/geoip
Log notice stdout
SocksListenAddress 127.0.0.1
SocksPort 9150
""")
        torrc.flush()

        devnull = os.open(os.devnull, os.O_RDONLY)
        proc = subprocess.Popen(["./App/tor", "-f", torrc.name],
                                close_fds=True,
                                stdin=devnull,
                                stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT)
        try:
            os.close(devnull)

            while True:
                line = proc.stdout.readline()
                sys.stdout.write(line)
                if line.endswith("Bootstrapped 100%: Done.\n"):
                    break
        finally:
            proc.terminate()
            proc.wait()

    # We do not want these files to be included in the primed cache.
    os.remove("Data/Tor/data/lock")
    os.remove("Data/Tor/data/state")

main()
