INSTALL = install
DESTDIR =
prefix  = /usr

all:
	# Nothing to do.

install:
	$(INSTALL) -d $(DESTDIR)$(prefix)/bin
	$(INSTALL) selenium-server.jar $(DESTDIR)$(prefix)/bin/selenium-server

.PHONY: all install
