#!/bin/sh

set -e

C=""
C="$C --apt-http-proxy http://127.0.0.1:8000/"
C="$C --architectures amd64"
C="$C --distribution sid"
C="$C --security false --backports false --updates false"

#C="$C --apt-recommends false"
C="$C --apt-indices false"
C="$C --memtest none"

set -x

cp ../pkg/*.deb config/packages.chroot/

lb config noauto $C "$@"
