#!/bin/sh

set -e

C=""
C="$C --apt-http-proxy http://127.0.0.1:8000/"
C="$C --architectures amd64"
C="$C --distribution sid"
C="$C --security false --backports false --updates false"

C="$C --apt-indices false"
C="$C --memtest none"

set -x

PKGDIR=config/packages.chroot
find "$PKGDIR" -maxdepth 1 -name '*.deb' -delete
cp ../pkg/*.deb "$PKGDIR"/

SSHDIR=config/includes.chroot/etc/skel/.ssh
if [ -f ../controller_identity.pub ]; then
  mkdir -p "$SSHDIR"/
  chmod 700 "$SSHDIR"/
  cp ../controller_identity.pub "$SSHDIR"/authorized_keys
  chmod 600 "$SSHDIR"/authorized_keys
fi

lb config noauto $C "$@"
