#! /usr/bin/perl -w
use List::Util qw(first);
my $here = first { $ARGV[$_] eq 'rsync' } 0..$#ARGV;
die "command line not as expected\n" unless defined $here;

my @newargs = @ARGV;

# This would be sudo -n -- but the sudo on PlanetLab
# is too old to support either option.
splice @newargs, $here, 0, 'sudo';
unshift @newargs, 'ssh';
exec @newargs
  or die "failed to execute ".join(' ', @newargs).": $!\n"
