#! /usr/bin/python3

# Bootstrap script for URL sources.
# Copyright © 2014 Zack Weinberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# There is NO WARRANTY.

import sys
import os
import os.path

# Sanitize sys.path - this is somewhat tedious.

scriptdir = os.path.dirname(__file__)
workdir   = os.getcwd()

def adjust_path(path):
    yield os.path.join(scriptdir, "lib")
    for p in path:
        p = os.path.abspath(p)
        if p != scriptdir and p != workdir:
            yield p

sys.path = list(adjust_path(sys.path))

# Now we know we will find the correct url_sources.

import url_sources
url_sources.driver()
